//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.Infrastructure.Storages;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace Ajuna.Infrastructure.RestService.Controller
{
    
    
    /// <summary>
    /// BoilerPlateController controller to access storages.
    /// </summary>
    [ApiController()]
    [Route("[controller]")]
    public sealed class BoilerPlateController : ControllerBase
    {
        
        private IBoilerPlateStorage _boilerPlateStorage;
        
        /// <summary>
        /// BoilerPlateController constructor.
        /// </summary>
        public BoilerPlateController(IBoilerPlateStorage boilerPlateStorage)
        {
            _boilerPlateStorage = boilerPlateStorage;
        }
        
        /// <summary>
        /// >> Something
        /// </summary>
        [HttpGet("Something")]
        [ProducesResponseType(typeof(Ajuna.NetApi.Model.Types.Primitive.U32), 200)]
        public IActionResult GetSomething()
        {
            return this.Ok(_boilerPlateStorage.GetSomething());
        }
    }
}
