//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.Infrastructure.Storages;
using Ajuna.NetApi.Model.PalletMatchmaker;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace Ajuna.Infrastructure.RestService.Controller
{
    
    
    /// <summary>
    /// ConnectFourMamaController controller to access storages.
    /// </summary>
    [ApiController()]
    [Route("[controller]")]
    public sealed class ConnectFourMamaController : ControllerBase
    {
        
        private IConnectFourMamaStorage _connectFourMamaStorage;
        
        /// <summary>
        /// ConnectFourMamaController constructor.
        /// </summary>
        public ConnectFourMamaController(IConnectFourMamaStorage connectFourMamaStorage)
        {
            _connectFourMamaStorage = connectFourMamaStorage;
        }
        
        /// <summary>
        /// >> BracketsCount
        /// </summary>
        [HttpGet("BracketsCount")]
        [ProducesResponseType(typeof(Ajuna.NetApi.Model.Types.Primitive.U8), 200)]
        public IActionResult GetBracketsCount()
        {
            return this.Ok(_connectFourMamaStorage.GetBracketsCount());
        }
        
        /// <summary>
        /// >> BracketIndices
        /// </summary>
        [HttpGet("BracketIndices")]
        [ProducesResponseType(typeof(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U16,Ajuna.NetApi.Model.Types.Primitive.U16>), 200)]
        public IActionResult GetBracketIndices(string key)
        {
            return this.Ok(_connectFourMamaStorage.GetBracketIndices(key));
        }
        
        /// <summary>
        /// >> BracketIndexKeyMap
        /// </summary>
        [HttpGet("BracketIndexKeyMap")]
        [ProducesResponseType(typeof(Ajuna.NetApi.Model.SpCore.AccountId32), 200)]
        public IActionResult GetBracketIndexKeyMap(string key)
        {
            return this.Ok(_connectFourMamaStorage.GetBracketIndexKeyMap(key));
        }
        
        /// <summary>
        /// >> BracketKeyValueMap
        /// </summary>
        [HttpGet("BracketKeyValueMap")]
        [ProducesResponseType(typeof(Ajuna.NetApi.Model.PalletMatchmaker.PlayerStruct), 200)]
        public IActionResult GetBracketKeyValueMap(string key)
        {
            return this.Ok(_connectFourMamaStorage.GetBracketKeyValueMap(key));
        }
    }
}
