//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.Infrastructure.Storages;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace Ajuna.Infrastructure.RestService.Controller
{
    
    
    /// <summary>
    /// IndicesController controller to access storages.
    /// </summary>
    [ApiController()]
    [Route("[controller]")]
    public sealed class IndicesController : ControllerBase
    {
        
        private IIndicesStorage _indicesStorage;
        
        /// <summary>
        /// IndicesController constructor.
        /// </summary>
        public IndicesController(IIndicesStorage indicesStorage)
        {
            _indicesStorage = indicesStorage;
        }
        
        /// <summary>
        /// >> Accounts
        ///  The lookup from index to account.
        /// </summary>
        [HttpGet("Accounts")]
        [ProducesResponseType(typeof(BaseTuple<Ajuna.NetApi.Model.SpCore.AccountId32,Ajuna.NetApi.Model.Types.Primitive.U128,Ajuna.NetApi.Model.Types.Primitive.Bool>), 200)]
        public IActionResult GetAccounts(string key)
        {
            return this.Ok(_indicesStorage.GetAccounts(key));
        }
    }
}
