//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletStaking
{
    
    
    /// <summary>
    /// >> 355 - Composite[pallet_staking.Nominations]
    /// </summary>
    public sealed class Nominations : BaseType
    {
        
        /// <summary>
        /// >> targets
        /// </summary>
        private BaseVec<Ajuna.NetApi.Model.SpCore.AccountId32> _targets;
        
        /// <summary>
        /// >> submitted_in
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _submittedIn;
        
        /// <summary>
        /// >> suppressed
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.Bool _suppressed;
        
        public BaseVec<Ajuna.NetApi.Model.SpCore.AccountId32> Targets
        {
            get
            {
                return this._targets;
            }
            set
            {
                this._targets = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 SubmittedIn
        {
            get
            {
                return this._submittedIn;
            }
            set
            {
                this._submittedIn = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.Bool Suppressed
        {
            get
            {
                return this._suppressed;
            }
            set
            {
                this._suppressed = value;
            }
        }
        
        public override string TypeName()
        {
            return "Nominations";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Targets.Encode());
            result.AddRange(SubmittedIn.Encode());
            result.AddRange(Suppressed.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Targets = new BaseVec<Ajuna.NetApi.Model.SpCore.AccountId32>();
            Targets.Decode(byteArray, ref p);
            SubmittedIn = new Ajuna.NetApi.Model.Types.Primitive.U32();
            SubmittedIn.Decode(byteArray, ref p);
            Suppressed = new Ajuna.NetApi.Model.Types.Primitive.Bool();
            Suppressed.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
