//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Extrinsics;
using Ajuna.NetApi.Model.Meta;
using Ajuna.NetApi.Model.NodeRuntime;
using Ajuna.NetApi.Model.SpRuntime;
using Ajuna.NetApi.Model.Types;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace Ajuna.NetApi.Model.PalletUtility
{
    
    
    public sealed class UtilityStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateClientExt _client;
        
        public UtilityStorage(SubstrateClientExt client)
        {
            this._client = client;
        }
    }
    
    public sealed class UtilityCalls
    {
        
        /// <summary>
        /// >> batch
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method Batch(BaseVec<Ajuna.NetApi.Model.NodeRuntime.EnumNodeCall> calls)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(calls.Encode());
            return new Method(1, "Utility", 0, "batch", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> as_derivative
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method AsDerivative(Ajuna.NetApi.Model.Types.Primitive.U16 index, Ajuna.NetApi.Model.NodeRuntime.EnumNodeCall call)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(index.Encode());
            byteArray.AddRange(call.Encode());
            return new Method(1, "Utility", 1, "as_derivative", byteArray.ToArray());
        }
        
        /// <summary>
        /// >> batch_all
        /// Contains one variant per dispatchable that can be called by an extrinsic.
        /// </summary>
        public static Method BatchAll(BaseVec<Ajuna.NetApi.Model.NodeRuntime.EnumNodeCall> calls)
        {
            System.Collections.Generic.List<byte> byteArray = new List<byte>();
            byteArray.AddRange(calls.Encode());
            return new Method(1, "Utility", 2, "batch_all", byteArray.ToArray());
        }
    }
    
    /// <summary>
    /// >> BatchInterrupted
    /// Batch of dispatches did not complete fully. Index of first failing dispatch given, as
    /// well as the error. \[index, error\]
    /// </summary>
    public sealed class EventBatchInterrupted : BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.SpRuntime.EnumDispatchError>
    {
    }
    
    /// <summary>
    /// >> BatchCompleted
    /// Batch of dispatches completed fully with no error.
    /// </summary>
    public sealed class EventBatchCompleted : BaseTuple
    {
    }
    
    /// <summary>
    /// >> ItemCompleted
    /// A single item within a Batch of dispatches has completed with no error.
    /// </summary>
    public sealed class EventItemCompleted : BaseTuple
    {
    }
    
    public enum UtilityErrors
    {
        
        /// <summary>
        /// >> TooManyCalls
        /// Too many calls batched.
        /// </summary>
        TooManyCalls,
    }
}
