//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.RestClient.Interfaces;
   using Ajuna.RestClient.Clients;
   
   public sealed class Client
   {
      private HttpClient _httpClient;
      public IAssetsControllerClient AssetsControllerClient;
      public IAuthorshipControllerClient AuthorshipControllerClient;
      public IBabeControllerClient BabeControllerClient;
      public IBagsListControllerClient BagsListControllerClient;
      public IBalancesControllerClient BalancesControllerClient;
      public IBoilerPlateControllerClient BoilerPlateControllerClient;
      public IBountiesControllerClient BountiesControllerClient;
      public IConnectFourControllerClient ConnectFourControllerClient;
      public IConnectFourMamaControllerClient ConnectFourMamaControllerClient;
      public IContractsControllerClient ContractsControllerClient;
      public ICouncilControllerClient CouncilControllerClient;
      public IDemocracyControllerClient DemocracyControllerClient;
      public IElectionProviderMultiPhaseControllerClient ElectionProviderMultiPhaseControllerClient;
      public IElectionsControllerClient ElectionsControllerClient;
      public IGiltControllerClient GiltControllerClient;
      public IGrandpaControllerClient GrandpaControllerClient;
      public IIdentityControllerClient IdentityControllerClient;
      public IImOnlineControllerClient ImOnlineControllerClient;
      public IIndicesControllerClient IndicesControllerClient;
      public ILotteryControllerClient LotteryControllerClient;
      public IMmrControllerClient MmrControllerClient;
      public IMultisigControllerClient MultisigControllerClient;
      public IOffencesControllerClient OffencesControllerClient;
      public IProxyControllerClient ProxyControllerClient;
      public IRandomnessCollectiveFlipControllerClient RandomnessCollectiveFlipControllerClient;
      public IRecoveryControllerClient RecoveryControllerClient;
      public ISchedulerControllerClient SchedulerControllerClient;
      public ISessionControllerClient SessionControllerClient;
      public ISocietyControllerClient SocietyControllerClient;
      public IStakingControllerClient StakingControllerClient;
      public ISudoControllerClient SudoControllerClient;
      public ISystemControllerClient SystemControllerClient;
      public ITechnicalCommitteeControllerClient TechnicalCommitteeControllerClient;
      public ITechnicalMembershipControllerClient TechnicalMembershipControllerClient;
      public ITimestampControllerClient TimestampControllerClient;
      public ITipsControllerClient TipsControllerClient;
      public ITransactionPaymentControllerClient TransactionPaymentControllerClient;
      public ITransactionStorageControllerClient TransactionStorageControllerClient;
      public ITreasuryControllerClient TreasuryControllerClient;
      public IUniquesControllerClient UniquesControllerClient;
      public IVestingControllerClient VestingControllerClient;
      public Client(HttpClient httpClient)
      {
         _httpClient = httpClient;
         AssetsControllerClient = new AssetsControllerClient(_httpClient);
         AuthorshipControllerClient = new AuthorshipControllerClient(_httpClient);
         BabeControllerClient = new BabeControllerClient(_httpClient);
         BagsListControllerClient = new BagsListControllerClient(_httpClient);
         BalancesControllerClient = new BalancesControllerClient(_httpClient);
         BoilerPlateControllerClient = new BoilerPlateControllerClient(_httpClient);
         BountiesControllerClient = new BountiesControllerClient(_httpClient);
         ConnectFourControllerClient = new ConnectFourControllerClient(_httpClient);
         ConnectFourMamaControllerClient = new ConnectFourMamaControllerClient(_httpClient);
         ContractsControllerClient = new ContractsControllerClient(_httpClient);
         CouncilControllerClient = new CouncilControllerClient(_httpClient);
         DemocracyControllerClient = new DemocracyControllerClient(_httpClient);
         ElectionProviderMultiPhaseControllerClient = new ElectionProviderMultiPhaseControllerClient(_httpClient);
         ElectionsControllerClient = new ElectionsControllerClient(_httpClient);
         GiltControllerClient = new GiltControllerClient(_httpClient);
         GrandpaControllerClient = new GrandpaControllerClient(_httpClient);
         IdentityControllerClient = new IdentityControllerClient(_httpClient);
         ImOnlineControllerClient = new ImOnlineControllerClient(_httpClient);
         IndicesControllerClient = new IndicesControllerClient(_httpClient);
         LotteryControllerClient = new LotteryControllerClient(_httpClient);
         MmrControllerClient = new MmrControllerClient(_httpClient);
         MultisigControllerClient = new MultisigControllerClient(_httpClient);
         OffencesControllerClient = new OffencesControllerClient(_httpClient);
         ProxyControllerClient = new ProxyControllerClient(_httpClient);
         RandomnessCollectiveFlipControllerClient = new RandomnessCollectiveFlipControllerClient(_httpClient);
         RecoveryControllerClient = new RecoveryControllerClient(_httpClient);
         SchedulerControllerClient = new SchedulerControllerClient(_httpClient);
         SessionControllerClient = new SessionControllerClient(_httpClient);
         SocietyControllerClient = new SocietyControllerClient(_httpClient);
         StakingControllerClient = new StakingControllerClient(_httpClient);
         SudoControllerClient = new SudoControllerClient(_httpClient);
         SystemControllerClient = new SystemControllerClient(_httpClient);
         TechnicalCommitteeControllerClient = new TechnicalCommitteeControllerClient(_httpClient);
         TechnicalMembershipControllerClient = new TechnicalMembershipControllerClient(_httpClient);
         TimestampControllerClient = new TimestampControllerClient(_httpClient);
         TipsControllerClient = new TipsControllerClient(_httpClient);
         TransactionPaymentControllerClient = new TransactionPaymentControllerClient(_httpClient);
         TransactionStorageControllerClient = new TransactionStorageControllerClient(_httpClient);
         TreasuryControllerClient = new TreasuryControllerClient(_httpClient);
         UniquesControllerClient = new UniquesControllerClient(_httpClient);
         VestingControllerClient = new VestingControllerClient(_httpClient);
      }
   }
}
