//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Base;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.Base
{
    
    
    /// <summary>
    /// >> 347 - Composite[BTreeMapT1]
    /// </summary>
    public sealed class BTreeMapT1 : BaseType
    {
        
        /// <summary>
        /// >> value
        /// </summary>
        private BaseVec<BaseTuple<Ajuna.NetApi.Model.Base.Arr3U128,Ajuna.NetApi.Model.Types.Primitive.U32>> _value;
        
        public BaseVec<BaseTuple<Ajuna.NetApi.Model.Base.Arr3U128,Ajuna.NetApi.Model.Types.Primitive.U32>> Value
        {
            get
            {
                return this._value;
            }
            set
            {
                this._value = value;
            }
        }
        
        public override string TypeName()
        {
            return "BTreeMapT1";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Value.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Value = new BaseVec<BaseTuple<Ajuna.NetApi.Model.Base.Arr3U128,Ajuna.NetApi.Model.Types.Primitive.U32>>();
            Value.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
