//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.PalletImOnline;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.FrameSupport
{
    
    
    /// <summary>
    /// >> 425 - Composite[frame_support.traits.misc.WrapperOpaque]
    /// </summary>
    public sealed class WrapperOpaque : BaseType
    {
        
        /// <summary>
        /// >> value0
        /// </summary>
        private BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> _value0;
        
        /// <summary>
        /// >> T
        /// </summary>
        private Ajuna.NetApi.Model.PalletImOnline.BoundedOpaqueNetworkState _t;
        
        public BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32> Value0
        {
            get
            {
                return this._value0;
            }
            set
            {
                this._value0 = value;
            }
        }
        
        public Ajuna.NetApi.Model.PalletImOnline.BoundedOpaqueNetworkState T
        {
            get
            {
                return this._t;
            }
            set
            {
                this._t = value;
            }
        }
        
        public override string TypeName()
        {
            return "WrapperOpaque";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Value0.Encode());
            result.AddRange(T.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Value0 = new BaseCom<Ajuna.NetApi.Model.Types.Primitive.U32>();
            Value0.Decode(byteArray, ref p);
            T = new Ajuna.NetApi.Model.PalletImOnline.BoundedOpaqueNetworkState();
            T.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
