//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.FrameSystem;
using Ajuna.NetApi.Model.PalletCollective;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.NodeRuntime
{
    
    
    public enum OriginCaller
    {
        
        system,
        
        Council,
        
        TechnicalCommittee,
        
        Void,
    }
    
    /// <summary>
    /// >> 464 - Variant[node_runtime.OriginCaller]
    /// </summary>
    public sealed class EnumOriginCaller : BaseEnumExt<OriginCaller, Ajuna.NetApi.Model.FrameSystem.EnumRawOrigin, Ajuna.NetApi.Model.PalletCollective.EnumRawOrigin, Ajuna.NetApi.Model.PalletCollective.EnumRawOrigin, Ajuna.NetApi.Model.Types.Base.BaseVoid>
    {
    }
}
