//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.SpCore;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class AuthorshipControllerClient : BaseClient, IAuthorshipControllerClient
   {
      private HttpClient _httpClient;
      public AuthorshipControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem>> GetUncles()
      {
         return await SendRequestAsync<BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem>>(_httpClient, "authorship/uncles");
      }
      public async Task<AccountId32> GetAuthor()
      {
         return await SendRequestAsync<AccountId32>(_httpClient, "authorship/author");
      }
      public async Task<Bool> GetDidSetUncles()
      {
         return await SendRequestAsync<Bool>(_httpClient, "authorship/didsetuncles");
      }
   }
}
