//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.PalletBagsList;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class BagsListControllerClient : BaseClient, IBagsListControllerClient
   {
      private HttpClient _httpClient;
      public BagsListControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<U32> GetCounterForListNodes()
      {
         return await SendRequestAsync<U32>(_httpClient, "bagslist/counterforlistnodes");
      }
      public async Task<Node> GetListNodes(string key)
      {
         return await SendRequestAsync<Node>(_httpClient, "bagslist/listnodes", key);
      }
      public async Task<Bag> GetListBags(string key)
      {
         return await SendRequestAsync<Bag>(_httpClient, "bagslist/listbags", key);
      }
   }
}
