//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.PalletBounties;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class BountiesControllerClient : BaseClient, IBountiesControllerClient
   {
      private HttpClient _httpClient;
      public BountiesControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<U32> GetBountyCount()
      {
         return await SendRequestAsync<U32>(_httpClient, "bounties/bountycount");
      }
      public async Task<Bounty> GetBounties(string key)
      {
         return await SendRequestAsync<Bounty>(_httpClient, "bounties/bounties", key);
      }
      public async Task<BaseVec<U8>> GetBountyDescriptions(string key)
      {
         return await SendRequestAsync<BaseVec<U8>>(_httpClient, "bounties/bountydescriptions", key);
      }
      public async Task<BaseVec<U32>> GetBountyApprovals()
      {
         return await SendRequestAsync<BaseVec<U32>>(_httpClient, "bounties/bountyapprovals");
      }
   }
}
