//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.SpCore;
   using Ajuna.NetApi.Model.PalletConnectfour;
   using Ajuna.NetApi.Model.PrimitiveTypes;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class ConnectFourControllerClient : BaseClient, IConnectFourControllerClient
   {
      private HttpClient _httpClient;
      public ConnectFourControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<U32> GetSomething()
      {
         return await SendRequestAsync<U32>(_httpClient, "connectfour/something");
      }
      public async Task<AccountId32> GetFounderKey()
      {
         return await SendRequestAsync<AccountId32>(_httpClient, "connectfour/founderkey");
      }
      public async Task<BoardStruct> GetBoards(string key)
      {
         return await SendRequestAsync<BoardStruct>(_httpClient, "connectfour/boards", key);
      }
      public async Task<H256> GetPlayerBoard(string key)
      {
         return await SendRequestAsync<H256>(_httpClient, "connectfour/playerboard", key);
      }
      public async Task<BaseOpt<BaseVec<U8>>> GetBoardSchedules(string key)
      {
         return await SendRequestAsync<BaseOpt<BaseVec<U8>>>(_httpClient, "connectfour/boardschedules", key);
      }
      public async Task<U64> GetNonce()
      {
         return await SendRequestAsync<U64>(_httpClient, "connectfour/nonce");
      }
   }
}
