//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.PalletContracts;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class ContractsControllerClient : BaseClient, IContractsControllerClient
   {
      private HttpClient _httpClient;
      public ContractsControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<BaseVec<U8>> GetPristineCode(string key)
      {
         return await SendRequestAsync<BaseVec<U8>>(_httpClient, "contracts/pristinecode", key);
      }
      public async Task<PrefabWasmModule> GetCodeStorage(string key)
      {
         return await SendRequestAsync<PrefabWasmModule>(_httpClient, "contracts/codestorage", key);
      }
      public async Task<U64> GetAccountCounter()
      {
         return await SendRequestAsync<U64>(_httpClient, "contracts/accountcounter");
      }
      public async Task<RawContractInfo> GetContractInfoOf(string key)
      {
         return await SendRequestAsync<RawContractInfo>(_httpClient, "contracts/contractinfoof", key);
      }
      public async Task<BaseVec<DeletedContract>> GetDeletionQueue()
      {
         return await SendRequestAsync<BaseVec<DeletedContract>>(_httpClient, "contracts/deletionqueue");
      }
   }
}
