//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.PalletElectionsPhragmen;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class ElectionsControllerClient : BaseClient, IElectionsControllerClient
   {
      private HttpClient _httpClient;
      public ElectionsControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<BaseVec<SeatHolder>> GetMembers()
      {
         return await SendRequestAsync<BaseVec<SeatHolder>>(_httpClient, "elections/members");
      }
      public async Task<BaseVec<SeatHolder>> GetRunnersUp()
      {
         return await SendRequestAsync<BaseVec<SeatHolder>>(_httpClient, "elections/runnersup");
      }
      public async Task<BaseVec<BaseTuple<Ajuna.NetApi.Model.SpCore.AccountId32, U128>>> GetCandidates()
      {
         return await SendRequestAsync<BaseVec<BaseTuple<Ajuna.NetApi.Model.SpCore.AccountId32, U128>>>(_httpClient, "elections/candidates");
      }
      public async Task<U32> GetElectionRounds()
      {
         return await SendRequestAsync<U32>(_httpClient, "elections/electionrounds");
      }
      public async Task<Voter> GetVoting(string key)
      {
         return await SendRequestAsync<Voter>(_httpClient, "elections/voting", key);
      }
   }
}
