//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.PrimitiveTypes;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class MmrControllerClient : BaseClient, IMmrControllerClient
   {
      private HttpClient _httpClient;
      public MmrControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<H256> GetRootHash()
      {
         return await SendRequestAsync<H256>(_httpClient, "mmr/roothash");
      }
      public async Task<U64> GetNumberOfLeaves()
      {
         return await SendRequestAsync<U64>(_httpClient, "mmr/numberofleaves");
      }
      public async Task<H256> GetNodes(string key)
      {
         return await SendRequestAsync<H256>(_httpClient, "mmr/nodes", key);
      }
   }
}
