//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.PalletMultisig;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class MultisigControllerClient : BaseClient, IMultisigControllerClient
   {
      private HttpClient _httpClient;
      public MultisigControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<Multisig> GetMultisigs(string key)
      {
         return await SendRequestAsync<Multisig>(_httpClient, "multisig/multisigs", key);
      }
      public async Task<BaseTuple<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>> GetCalls(string key)
      {
         return await SendRequestAsync<BaseTuple<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>, Ajuna.NetApi.Model.SpCore.AccountId32, Ajuna.NetApi.Model.Types.Primitive.U128>>(_httpClient, "multisig/calls", key);
      }
   }
}
