//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class RandomnessCollectiveFlipControllerClient : BaseClient, IRandomnessCollectiveFlipControllerClient
   {
      private HttpClient _httpClient;
      public RandomnessCollectiveFlipControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256>> GetRandomMaterial()
      {
         return await SendRequestAsync<BaseVec<Ajuna.NetApi.Model.PrimitiveTypes.H256>>(_httpClient, "randomnesscollectiveflip/randommaterial");
      }
   }
}
