//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.PalletTips;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class TipsControllerClient : BaseClient, ITipsControllerClient
   {
      private HttpClient _httpClient;
      public TipsControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<OpenTip> GetTips(string key)
      {
         return await SendRequestAsync<OpenTip>(_httpClient, "tips/tips", key);
      }
      public async Task<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>> GetReasons(string key)
      {
         return await SendRequestAsync<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>>(_httpClient, "tips/reasons", key);
      }
   }
}
