//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.PalletTreasury;
   using Ajuna.NetApi.Model.FrameSupport;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class TreasuryControllerClient : BaseClient, ITreasuryControllerClient
   {
      private HttpClient _httpClient;
      public TreasuryControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<U32> GetProposalCount()
      {
         return await SendRequestAsync<U32>(_httpClient, "treasury/proposalcount");
      }
      public async Task<Proposal> GetProposals(string key)
      {
         return await SendRequestAsync<Proposal>(_httpClient, "treasury/proposals", key);
      }
      public async Task<BoundedVecT9> GetApprovals()
      {
         return await SendRequestAsync<BoundedVecT9>(_httpClient, "treasury/approvals");
      }
   }
}
