//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Clients
{
   using System;
   using System.Threading.Tasks;
   using System.Net.Http;
   using Ajuna.NetApi.Model.PalletUniques;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.RestClient.Interfaces;
   
   public sealed class UniquesControllerClient : BaseClient, IUniquesControllerClient
   {
      private HttpClient _httpClient;
      public UniquesControllerClient(HttpClient httpClient)
      {
         _httpClient = httpClient;
      }
      public async Task<ClassDetails> GetClass(string key)
      {
         return await SendRequestAsync<ClassDetails>(_httpClient, "uniques/class", key);
      }
      public async Task<BaseTuple> GetAccount(string key)
      {
         return await SendRequestAsync<BaseTuple>(_httpClient, "uniques/account", key);
      }
      public async Task<InstanceDetails> GetAsset(string key)
      {
         return await SendRequestAsync<InstanceDetails>(_httpClient, "uniques/asset", key);
      }
      public async Task<ClassMetadata> GetClassMetadataOf(string key)
      {
         return await SendRequestAsync<ClassMetadata>(_httpClient, "uniques/classmetadataof", key);
      }
      public async Task<InstanceMetadata> GetInstanceMetadataOf(string key)
      {
         return await SendRequestAsync<InstanceMetadata>(_httpClient, "uniques/instancemetadataof", key);
      }
      public async Task<BaseTuple<Ajuna.NetApi.Model.FrameSupport.BoundedVecT3, Ajuna.NetApi.Model.Types.Primitive.U128>> GetAttribute(string key)
      {
         return await SendRequestAsync<BaseTuple<Ajuna.NetApi.Model.FrameSupport.BoundedVecT3, Ajuna.NetApi.Model.Types.Primitive.U128>>(_httpClient, "uniques/attribute", key);
      }
   }
}
