//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.SpCore;
   using Ajuna.NetApi.Model.Types.Primitive;
   
   public interface IAuthorshipControllerClient
   {
      Task<BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem>> GetUncles();
      Task<AccountId32> GetAuthor();
      Task<Bool> GetDidSetUncles();
   }
}
