//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.PalletBagsList;
   
   public interface IBagsListControllerClient
   {
      Task<U32> GetCounterForListNodes();
      Task<Node> GetListNodes(string key);
      Task<Bag> GetListBags(string key);
   }
}
