//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.SpCore;
   using Ajuna.NetApi.Model.PalletMatchmaker;
   
   public interface IConnectFourMamaControllerClient
   {
      Task<U8> GetBracketsCount();
      Task<BaseTuple<U16, U16>> GetBracketIndices(string key);
      Task<AccountId32> GetBracketIndexKeyMap(string key);
      Task<PlayerStruct> GetBracketKeyValueMap(string key);
   }
}
