//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.PalletElectionProviderMultiPhase;
   using Ajuna.NetApi.Model.FrameSupport;
   using Ajuna.NetApi.Model.Base;
   
   public interface IElectionProviderMultiPhaseControllerClient
   {
      Task<U32> GetRound();
      Task<EnumPhase> GetCurrentPhase();
      Task<ReadySolution> GetQueuedSolution();
      Task<RoundSnapshot> GetSnapshot();
      Task<U32> GetDesiredTargets();
      Task<SolutionOrSnapshotSize> GetSnapshotMetadata();
      Task<U32> GetSignedSubmissionNextIndex();
      Task<BoundedBTreeMap> GetSignedSubmissionIndices();
      Task<SignedSubmission> GetSignedSubmissionsMap(string key);
      Task<Arr3U128> GetMinimumUntrustedScore();
   }
}
