//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.PalletGrandpa;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.Types.Base;
   
   public interface IGrandpaControllerClient
   {
      Task<EnumStoredState> GetState();
      Task<StoredPendingChange> GetPendingChange();
      Task<U32> GetNextForced();
      Task<BaseTuple<U32, U32>> GetStalled();
      Task<U64> GetCurrentSetId();
      Task<U32> GetSetIdSession(string key);
   }
}
