//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.PalletIdentity;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.FrameSupport;
   
   public interface IIdentityControllerClient
   {
      Task<Registration> GetIdentityOf(string key);
      Task<BaseTuple<Ajuna.NetApi.Model.SpCore.AccountId32, EnumData>> GetSuperOf(string key);
      Task<BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U128, BoundedVecT11>> GetSubsOf(string key);
      Task<BoundedVecT12> GetRegistrars();
   }
}
