//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.FrameSupport;
   
   public interface IImOnlineControllerClient
   {
      Task<U32> GetHeartbeatAfter();
      Task<WeakBoundedVecT4> GetKeys();
      Task<WrapperOpaque> GetReceivedHeartbeats(string key);
      Task<U32> GetAuthoredBlocks(string key);
   }
}
