//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.PrimitiveTypes;
   using Ajuna.NetApi.Model.Types.Primitive;
   
   public interface IMmrControllerClient
   {
      Task<H256> GetRootHash();
      Task<U64> GetNumberOfLeaves();
      Task<H256> GetNodes(string key);
   }
}
