//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Base;
   
   public interface IProxyControllerClient
   {
      Task<BaseTuple<Ajuna.NetApi.Model.FrameSupport.BoundedVecT14, Ajuna.NetApi.Model.Types.Primitive.U128>> GetProxies(string key);
      Task<BaseTuple<Ajuna.NetApi.Model.FrameSupport.BoundedVecT15, Ajuna.NetApi.Model.Types.Primitive.U128>> GetAnnouncements(string key);
   }
}
