//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.PalletRecovery;
   using Ajuna.NetApi.Model.SpCore;
   
   public interface IRecoveryControllerClient
   {
      Task<RecoveryConfig> GetRecoverable(string key);
      Task<ActiveRecovery> GetActiveRecoveries(string key);
      Task<AccountId32> GetProxy(string key);
   }
}
