//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.PalletScheduler;
   
   public interface ISchedulerControllerClient
   {
      Task<BaseVec<BaseOpt<ScheduledV2>>> GetAgenda(string key);
      Task<BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U32, Ajuna.NetApi.Model.Types.Primitive.U32>> GetLookup(string key);
      Task<EnumReleases> GetStorageVersion();
   }
}
