//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.Types.Primitive;
   using Ajuna.NetApi.Model.NodeRuntime;
   using Ajuna.NetApi.Model.SpCore;
   
   public interface ISessionControllerClient
   {
      Task<BaseVec<AccountId32>> GetValidators();
      Task<U32> GetCurrentIndex();
      Task<Bool> GetQueuedChanged();
      Task<BaseVec<BaseTuple<AccountId32, SessionKeys>>> GetQueuedKeys();
      Task<BaseVec<U32>> GetDisabledValidators();
      Task<SessionKeys> GetNextKeys(string key);
      Task<AccountId32> GetKeyOwner(string key);
   }
}
