//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.Types.Base;
   using Ajuna.NetApi.Model.Types.Primitive;
   
   public interface ITransactionStorageControllerClient
   {
      Task<BaseVec<Ajuna.NetApi.Model.PalletTransactionStorage.TransactionInfo>> GetTransactions(string key);
      Task<U32> GetChunkCount(string key);
      Task<U128> GetByteFee();
      Task<U128> GetEntryFee();
      Task<U32> GetMaxTransactionSize();
      Task<U32> GetMaxBlockTransactions();
      Task<U32> GetStoragePeriod();
      Task<BaseVec<Ajuna.NetApi.Model.PalletTransactionStorage.TransactionInfo>> GetBlockTransactions();
      Task<Bool> GetProofChecked();
   }
}
