//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajuna.RestClient.Interfaces
{
   using System;
   using System.Threading.Tasks;
   using Ajuna.NetApi.Model.SpArithmetic;
   using Ajuna.NetApi.Model.PalletTransactionPayment;
   
   public interface ITransactionPaymentControllerClient
   {
      Task<FixedU128> GetNextFeeMultiplier();
      Task<EnumReleases> GetStorageVersion();
   }
}
