//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.SpCore
{
    
    
    /// <summary>
    /// >> 239 - Composite[sp_core.offchain.OpaqueNetworkState]
    /// </summary>
    public sealed class OpaqueNetworkState : BaseType
    {
        
        /// <summary>
        /// >> peer_id
        /// </summary>
        private Ajuna.NetApi.Model.SpCore.OpaquePeerId _peerId;
        
        /// <summary>
        /// >> external_addresses
        /// </summary>
        private BaseVec<Ajuna.NetApi.Model.SpCore.OpaqueMultiaddr> _externalAddresses;
        
        public Ajuna.NetApi.Model.SpCore.OpaquePeerId PeerId
        {
            get
            {
                return this._peerId;
            }
            set
            {
                this._peerId = value;
            }
        }
        
        public BaseVec<Ajuna.NetApi.Model.SpCore.OpaqueMultiaddr> ExternalAddresses
        {
            get
            {
                return this._externalAddresses;
            }
            set
            {
                this._externalAddresses = value;
            }
        }
        
        public override string TypeName()
        {
            return "OpaqueNetworkState";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(PeerId.Encode());
            result.AddRange(ExternalAddresses.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            PeerId = new Ajuna.NetApi.Model.SpCore.OpaquePeerId();
            PeerId.Decode(byteArray, ref p);
            ExternalAddresses = new BaseVec<Ajuna.NetApi.Model.SpCore.OpaqueMultiaddr>();
            ExternalAddresses.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
