//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.PalletMultisig;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletMultisig
{
    
    
    /// <summary>
    /// >> 481 - Composite[pallet_multisig.Multisig]
    /// </summary>
    public sealed class Multisig : BaseType
    {
        
        /// <summary>
        /// >> when
        /// </summary>
        private Ajuna.NetApi.Model.PalletMultisig.Timepoint _when;
        
        /// <summary>
        /// >> deposit
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U128 _deposit;
        
        /// <summary>
        /// >> depositor
        /// </summary>
        private Ajuna.NetApi.Model.SpCore.AccountId32 _depositor;
        
        /// <summary>
        /// >> approvals
        /// </summary>
        private BaseVec<Ajuna.NetApi.Model.SpCore.AccountId32> _approvals;
        
        public Ajuna.NetApi.Model.PalletMultisig.Timepoint When
        {
            get
            {
                return this._when;
            }
            set
            {
                this._when = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U128 Deposit
        {
            get
            {
                return this._deposit;
            }
            set
            {
                this._deposit = value;
            }
        }
        
        public Ajuna.NetApi.Model.SpCore.AccountId32 Depositor
        {
            get
            {
                return this._depositor;
            }
            set
            {
                this._depositor = value;
            }
        }
        
        public BaseVec<Ajuna.NetApi.Model.SpCore.AccountId32> Approvals
        {
            get
            {
                return this._approvals;
            }
            set
            {
                this._approvals = value;
            }
        }
        
        public override string TypeName()
        {
            return "Multisig";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(When.Encode());
            result.AddRange(Deposit.Encode());
            result.AddRange(Depositor.Encode());
            result.AddRange(Approvals.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            When = new Ajuna.NetApi.Model.PalletMultisig.Timepoint();
            When.Decode(byteArray, ref p);
            Deposit = new Ajuna.NetApi.Model.Types.Primitive.U128();
            Deposit.Decode(byteArray, ref p);
            Depositor = new Ajuna.NetApi.Model.SpCore.AccountId32();
            Depositor.Decode(byteArray, ref p);
            Approvals = new BaseVec<Ajuna.NetApi.Model.SpCore.AccountId32>();
            Approvals.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
