//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.PalletAuthorship;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using Ajuna.ServiceLayer.Attributes;
using Ajuna.ServiceLayer.Storage;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace Ajuna.Infrastructure.Storages
{
    
    
    public interface IAuthorshipStorage : IStorage
    {
        
        /// <summary>
        /// >> Uncles
        ///  Uncles
        /// </summary>
        BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem> GetUncles();
        
        /// <summary>
        /// >> Author
        ///  Author of current block.
        /// </summary>
        Ajuna.NetApi.Model.SpCore.AccountId32 GetAuthor();
        
        /// <summary>
        /// >> DidSetUncles
        ///  Whether uncles were already set in this block.
        /// </summary>
        Ajuna.NetApi.Model.Types.Primitive.Bool GetDidSetUncles();
    }
    
    public sealed class AuthorshipStorage : IAuthorshipStorage
    {
        
        private TypedStorage<BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem>> _unclesTypedStorage;
        
        private TypedStorage<Ajuna.NetApi.Model.SpCore.AccountId32> _authorTypedStorage;
        
        private TypedStorage<Ajuna.NetApi.Model.Types.Primitive.Bool> _didSetUnclesTypedStorage;
        
        public AuthorshipStorage(IStorageChangeDelegate storageChangeDelegate)
        {
            this.UnclesTypedStorage = new TypedStorage<BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem>>("Authorship.Uncles", storageChangeDelegate);
            this.AuthorTypedStorage = new TypedStorage<Ajuna.NetApi.Model.SpCore.AccountId32>("Authorship.Author", storageChangeDelegate);
            this.DidSetUnclesTypedStorage = new TypedStorage<Ajuna.NetApi.Model.Types.Primitive.Bool>("Authorship.DidSetUncles", storageChangeDelegate);
        }
        
        public TypedStorage<BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem>> UnclesTypedStorage
        {
            get
            {
                return _unclesTypedStorage;
            }
            set
            {
                _unclesTypedStorage = value;
            }
        }
        
        public TypedStorage<Ajuna.NetApi.Model.SpCore.AccountId32> AuthorTypedStorage
        {
            get
            {
                return _authorTypedStorage;
            }
            set
            {
                _authorTypedStorage = value;
            }
        }
        
        public TypedStorage<Ajuna.NetApi.Model.Types.Primitive.Bool> DidSetUnclesTypedStorage
        {
            get
            {
                return _didSetUnclesTypedStorage;
            }
            set
            {
                _didSetUnclesTypedStorage = value;
            }
        }
        
        public async Task InitializeAsync(Ajuna.NetApi.SubstrateClient client)
        {
            await UnclesTypedStorage.InitializeAsync(client, "Authorship", "Uncles");
            await AuthorTypedStorage.InitializeAsync(client, "Authorship", "Author");
            await DidSetUnclesTypedStorage.InitializeAsync(client, "Authorship", "DidSetUncles");
        }
        
        [StorageChange("Authorship", "Uncles")]
        public void OnUpdateUncles(string data)
        {
            UnclesTypedStorage.Update(data);
        }
        
        /// <summary>
        /// >> Uncles
        ///  Uncles
        /// </summary>
        public BaseVec<Ajuna.NetApi.Model.PalletAuthorship.EnumUncleEntryItem> GetUncles()
        {
            return UnclesTypedStorage.Get();
        }
        
        [StorageChange("Authorship", "Author")]
        public void OnUpdateAuthor(string data)
        {
            AuthorTypedStorage.Update(data);
        }
        
        /// <summary>
        /// >> Author
        ///  Author of current block.
        /// </summary>
        public Ajuna.NetApi.Model.SpCore.AccountId32 GetAuthor()
        {
            return AuthorTypedStorage.Get();
        }
        
        [StorageChange("Authorship", "DidSetUncles")]
        public void OnUpdateDidSetUncles(string data)
        {
            DidSetUnclesTypedStorage.Update(data);
        }
        
        /// <summary>
        /// >> DidSetUncles
        ///  Whether uncles were already set in this block.
        /// </summary>
        public Ajuna.NetApi.Model.Types.Primitive.Bool GetDidSetUncles()
        {
            return DidSetUnclesTypedStorage.Get();
        }
    }
}
