//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.PalletTips;
using Ajuna.NetApi.Model.PrimitiveTypes;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using Ajuna.ServiceLayer.Attributes;
using Ajuna.ServiceLayer.Storage;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace Ajuna.Infrastructure.Storages
{
    
    
    public interface ITipsStorage : IStorage
    {
        
        /// <summary>
        /// >> Tips
        ///  TipsMap that are not yet completed. Keyed by the hash of `(reason, who)` from the value.
        ///  This has the insecure enumerable hash function since the key itself is already
        ///  guaranteed to be a secure hash.
        /// </summary>
        Ajuna.NetApi.Model.PalletTips.OpenTip GetTips(string key);
        
        /// <summary>
        /// >> Reasons
        ///  Simple preimage lookup from the reason&#39;s hash to the original data. Again, has an
        ///  insecure enumerable hash since the key is guaranteed to be the result of a secure hash.
        /// </summary>
        BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> GetReasons(string key);
    }
    
    public sealed class TipsStorage : ITipsStorage
    {
        
        private TypedMapStorage<Ajuna.NetApi.Model.PalletTips.OpenTip> _tipsTypedStorage;
        
        private TypedMapStorage<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>> _reasonsTypedStorage;
        
        public TipsStorage(IStorageChangeDelegate storageChangeDelegate)
        {
            this.TipsTypedStorage = new TypedMapStorage<Ajuna.NetApi.Model.PalletTips.OpenTip>("Tips.Tips", storageChangeDelegate);
            this.ReasonsTypedStorage = new TypedMapStorage<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>>("Tips.Reasons", storageChangeDelegate);
        }
        
        public TypedMapStorage<Ajuna.NetApi.Model.PalletTips.OpenTip> TipsTypedStorage
        {
            get
            {
                return _tipsTypedStorage;
            }
            set
            {
                _tipsTypedStorage = value;
            }
        }
        
        public TypedMapStorage<BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8>> ReasonsTypedStorage
        {
            get
            {
                return _reasonsTypedStorage;
            }
            set
            {
                _reasonsTypedStorage = value;
            }
        }
        
        public async Task InitializeAsync(Ajuna.NetApi.SubstrateClient client)
        {
            await TipsTypedStorage.InitializeAsync(client, "Tips", "Tips");
            await ReasonsTypedStorage.InitializeAsync(client, "Tips", "Reasons");
        }
        
        [StorageChange("Tips", "Tips")]
        public void OnUpdateTips(string key, string data)
        {
            TipsTypedStorage.Update(key, data);
        }
        
        /// <summary>
        /// >> Tips
        ///  TipsMap that are not yet completed. Keyed by the hash of `(reason, who)` from the value.
        ///  This has the insecure enumerable hash function since the key itself is already
        ///  guaranteed to be a secure hash.
        /// </summary>
        public Ajuna.NetApi.Model.PalletTips.OpenTip GetTips(string key)
        {
            if ((key == null))
            {
                return null;
            }
            if (TipsTypedStorage.Dictionary.TryGetValue(key, out Ajuna.NetApi.Model.PalletTips.OpenTip result))
            {
                return result;
            }
            else
            {
                return null;
            }
        }
        
        [StorageChange("Tips", "Reasons")]
        public void OnUpdateReasons(string key, string data)
        {
            ReasonsTypedStorage.Update(key, data);
        }
        
        /// <summary>
        /// >> Reasons
        ///  Simple preimage lookup from the reason&#39;s hash to the original data. Again, has an
        ///  insecure enumerable hash since the key is guaranteed to be the result of a secure hash.
        /// </summary>
        public BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> GetReasons(string key)
        {
            if ((key == null))
            {
                return null;
            }
            if (ReasonsTypedStorage.Dictionary.TryGetValue(key, out BaseVec<Ajuna.NetApi.Model.Types.Primitive.U8> result))
            {
                return result;
            }
            else
            {
                return null;
            }
        }
    }
}
