//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.FrameSupport;
using Ajuna.NetApi.Model.PalletVesting;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.ServiceLayer.Attributes;
using Ajuna.ServiceLayer.Storage;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;


namespace Ajuna.Infrastructure.Storages
{
    
    
    public interface IVestingStorage : IStorage
    {
        
        /// <summary>
        /// >> Vesting
        ///  Information regarding the vesting of a given account.
        /// </summary>
        Ajuna.NetApi.Model.FrameSupport.BoundedVecT13 GetVesting(string key);
        
        /// <summary>
        /// >> StorageVersion
        ///  Storage version of the pallet.
        /// 
        ///  New networks start with latest version, as determined by the genesis build.
        /// </summary>
        Ajuna.NetApi.Model.PalletVesting.EnumReleases GetStorageVersion();
    }
    
    public sealed class VestingStorage : IVestingStorage
    {
        
        private TypedMapStorage<Ajuna.NetApi.Model.FrameSupport.BoundedVecT13> _vestingTypedStorage;
        
        private TypedStorage<Ajuna.NetApi.Model.PalletVesting.EnumReleases> _storageVersionTypedStorage;
        
        public VestingStorage(IStorageChangeDelegate storageChangeDelegate)
        {
            this.VestingTypedStorage = new TypedMapStorage<Ajuna.NetApi.Model.FrameSupport.BoundedVecT13>("Vesting.Vesting", storageChangeDelegate);
            this.StorageVersionTypedStorage = new TypedStorage<Ajuna.NetApi.Model.PalletVesting.EnumReleases>("Vesting.StorageVersion", storageChangeDelegate);
        }
        
        public TypedMapStorage<Ajuna.NetApi.Model.FrameSupport.BoundedVecT13> VestingTypedStorage
        {
            get
            {
                return _vestingTypedStorage;
            }
            set
            {
                _vestingTypedStorage = value;
            }
        }
        
        public TypedStorage<Ajuna.NetApi.Model.PalletVesting.EnumReleases> StorageVersionTypedStorage
        {
            get
            {
                return _storageVersionTypedStorage;
            }
            set
            {
                _storageVersionTypedStorage = value;
            }
        }
        
        public async Task InitializeAsync(Ajuna.NetApi.SubstrateClient client)
        {
            await VestingTypedStorage.InitializeAsync(client, "Vesting", "Vesting");
            await StorageVersionTypedStorage.InitializeAsync(client, "Vesting", "StorageVersion");
        }
        
        [StorageChange("Vesting", "Vesting")]
        public void OnUpdateVesting(string key, string data)
        {
            VestingTypedStorage.Update(key, data);
        }
        
        /// <summary>
        /// >> Vesting
        ///  Information regarding the vesting of a given account.
        /// </summary>
        public Ajuna.NetApi.Model.FrameSupport.BoundedVecT13 GetVesting(string key)
        {
            if ((key == null))
            {
                return null;
            }
            if (VestingTypedStorage.Dictionary.TryGetValue(key, out Ajuna.NetApi.Model.FrameSupport.BoundedVecT13 result))
            {
                return result;
            }
            else
            {
                return null;
            }
        }
        
        [StorageChange("Vesting", "StorageVersion")]
        public void OnUpdateStorageVersion(string data)
        {
            StorageVersionTypedStorage.Update(data);
        }
        
        /// <summary>
        /// >> StorageVersion
        ///  Storage version of the pallet.
        /// 
        ///  New networks start with latest version, as determined by the genesis build.
        /// </summary>
        public Ajuna.NetApi.Model.PalletVesting.EnumReleases GetStorageVersion()
        {
            return StorageVersionTypedStorage.Get();
        }
    }
}
