//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletLottery
{
    
    
    /// <summary>
    /// >> 495 - Composite[pallet_lottery.LotteryConfig]
    /// </summary>
    public sealed class LotteryConfig : BaseType
    {
        
        /// <summary>
        /// >> price
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U128 _price;
        
        /// <summary>
        /// >> start
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _start;
        
        /// <summary>
        /// >> length
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _length;
        
        /// <summary>
        /// >> delay
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.U32 _delay;
        
        /// <summary>
        /// >> repeat
        /// </summary>
        private Ajuna.NetApi.Model.Types.Primitive.Bool _repeat;
        
        public Ajuna.NetApi.Model.Types.Primitive.U128 Price
        {
            get
            {
                return this._price;
            }
            set
            {
                this._price = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 Start
        {
            get
            {
                return this._start;
            }
            set
            {
                this._start = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 Length
        {
            get
            {
                return this._length;
            }
            set
            {
                this._length = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.U32 Delay
        {
            get
            {
                return this._delay;
            }
            set
            {
                this._delay = value;
            }
        }
        
        public Ajuna.NetApi.Model.Types.Primitive.Bool Repeat
        {
            get
            {
                return this._repeat;
            }
            set
            {
                this._repeat = value;
            }
        }
        
        public override string TypeName()
        {
            return "LotteryConfig";
        }
        
        public override byte[] Encode()
        {
            var result = new List<byte>();
            result.AddRange(Price.Encode());
            result.AddRange(Start.Encode());
            result.AddRange(Length.Encode());
            result.AddRange(Delay.Encode());
            result.AddRange(Repeat.Encode());
            return result.ToArray();
        }
        
        public override void Decode(byte[] byteArray, ref int p)
        {
            var start = p;
            Price = new Ajuna.NetApi.Model.Types.Primitive.U128();
            Price.Decode(byteArray, ref p);
            Start = new Ajuna.NetApi.Model.Types.Primitive.U32();
            Start.Decode(byteArray, ref p);
            Length = new Ajuna.NetApi.Model.Types.Primitive.U32();
            Length.Decode(byteArray, ref p);
            Delay = new Ajuna.NetApi.Model.Types.Primitive.U32();
            Delay.Decode(byteArray, ref p);
            Repeat = new Ajuna.NetApi.Model.Types.Primitive.Bool();
            Repeat.Decode(byteArray, ref p);
            TypeSize = p - start;
        }
    }
}
