//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.PalletSociety
{
    
    
    public enum Vote
    {
        
        Skeptic,
        
        Reject,
        
        Approve,
    }
    
    /// <summary>
    /// >> 452 - Variant[pallet_society.Vote]
    /// </summary>
    public sealed class EnumVote : BaseEnum<Vote>
    {
    }
}
