//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Extrinsics;
using Ajuna.NetApi.Model.Meta;
using Ajuna.NetApi.Model.PalletMatchmaker;
using Ajuna.NetApi.Model.SpCore;
using Ajuna.NetApi.Model.Types;
using Ajuna.NetApi.Model.Types.Base;
using Ajuna.NetApi.Model.Types.Primitive;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;


namespace Ajuna.NetApi.Model.PalletConnectFourMama
{
    
    
    public sealed class ConnectFourMamaStorage
    {
        
        // Substrate client for the storage calls.
        private SubstrateClientExt _client;
        
        public ConnectFourMamaStorage(SubstrateClientExt client)
        {
            this._client = client;
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("ConnectFourMama", "BracketsCount"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(null, null, typeof(Ajuna.NetApi.Model.Types.Primitive.U8)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("ConnectFourMama", "BracketIndices"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(Ajuna.NetApi.Model.Types.Primitive.U8), typeof(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U16,Ajuna.NetApi.Model.Types.Primitive.U16>)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("ConnectFourMama", "BracketIndexKeyMap"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U8,Ajuna.NetApi.Model.Types.Primitive.U16>), typeof(Ajuna.NetApi.Model.SpCore.AccountId32)));
            _client.StorageKeyDict.Add(new System.Tuple<string, string>("ConnectFourMama", "BracketKeyValueMap"), new System.Tuple<Ajuna.NetApi.Model.Meta.Storage.Hasher[], System.Type, System.Type>(new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                            Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, typeof(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U8,Ajuna.NetApi.Model.SpCore.AccountId32>), typeof(Ajuna.NetApi.Model.PalletMatchmaker.PlayerStruct)));
        }
        
        /// <summary>
        /// >> BracketsCountParams
        /// </summary>
        public static string BracketsCountParams()
        {
            return RequestGenerator.GetStorage("ConnectFourMama", "BracketsCount", Ajuna.NetApi.Model.Meta.Storage.Type.Plain);
        }
        
        /// <summary>
        /// >> BracketsCount
        /// </summary>
        public async Task<Ajuna.NetApi.Model.Types.Primitive.U8> BracketsCount(CancellationToken token)
        {
            string parameters = ConnectFourMamaStorage.BracketsCountParams();
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.Types.Primitive.U8>(parameters, token);
        }
        
        /// <summary>
        /// >> BracketIndicesParams
        /// </summary>
        public static string BracketIndicesParams(Ajuna.NetApi.Model.Types.Primitive.U8 key)
        {
            return RequestGenerator.GetStorage("ConnectFourMama", "BracketIndices", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> BracketIndices
        /// </summary>
        public async Task<BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U16,Ajuna.NetApi.Model.Types.Primitive.U16>> BracketIndices(Ajuna.NetApi.Model.Types.Primitive.U8 key, CancellationToken token)
        {
            string parameters = ConnectFourMamaStorage.BracketIndicesParams(key);
            return await _client.GetStorageAsync<BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U16,Ajuna.NetApi.Model.Types.Primitive.U16>>(parameters, token);
        }
        
        /// <summary>
        /// >> BracketIndexKeyMapParams
        /// </summary>
        public static string BracketIndexKeyMapParams(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U8,Ajuna.NetApi.Model.Types.Primitive.U16> key)
        {
            return RequestGenerator.GetStorage("ConnectFourMama", "BracketIndexKeyMap", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> BracketIndexKeyMap
        /// </summary>
        public async Task<Ajuna.NetApi.Model.SpCore.AccountId32> BracketIndexKeyMap(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U8,Ajuna.NetApi.Model.Types.Primitive.U16> key, CancellationToken token)
        {
            string parameters = ConnectFourMamaStorage.BracketIndexKeyMapParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.SpCore.AccountId32>(parameters, token);
        }
        
        /// <summary>
        /// >> BracketKeyValueMapParams
        /// </summary>
        public static string BracketKeyValueMapParams(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U8,Ajuna.NetApi.Model.SpCore.AccountId32> key)
        {
            return RequestGenerator.GetStorage("ConnectFourMama", "BracketKeyValueMap", Ajuna.NetApi.Model.Meta.Storage.Type.Map, new Ajuna.NetApi.Model.Meta.Storage.Hasher[] {
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat,
                        Ajuna.NetApi.Model.Meta.Storage.Hasher.BlakeTwo128Concat}, new Ajuna.NetApi.Model.Types.IType[] {
                        key});
        }
        
        /// <summary>
        /// >> BracketKeyValueMap
        /// </summary>
        public async Task<Ajuna.NetApi.Model.PalletMatchmaker.PlayerStruct> BracketKeyValueMap(BaseTuple<Ajuna.NetApi.Model.Types.Primitive.U8,Ajuna.NetApi.Model.SpCore.AccountId32> key, CancellationToken token)
        {
            string parameters = ConnectFourMamaStorage.BracketKeyValueMapParams(key);
            return await _client.GetStorageAsync<Ajuna.NetApi.Model.PalletMatchmaker.PlayerStruct>(parameters, token);
        }
    }
    
    public sealed class ConnectFourMamaCalls
    {
    }
    
    /// <summary>
    /// >> Queued
    /// Queued event
    /// </summary>
    public sealed class EventQueued : BaseTuple<Ajuna.NetApi.Model.PalletMatchmaker.PlayerStruct>
    {
    }
    
    /// <summary>
    /// >> Popped
    /// Popped event
    /// </summary>
    public sealed class EventPopped : BaseTuple<Ajuna.NetApi.Model.PalletMatchmaker.PlayerStruct>
    {
    }
    
    public enum ConnectFourMamaErrors
    {
        
        /// <summary>
        /// >> QueueSizeToLow
        /// Queue size is to low.
        /// </summary>
        QueueSizeToLow,
        
        /// <summary>
        /// >> QueueIsEmpty
        /// Queue is empty.
        /// </summary>
        QueueIsEmpty,
    }
}
