//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Ajuna.NetApi.Model.Types.Base;
using System;
using System.Collections.Generic;


namespace Ajuna.NetApi.Model.SpConsensusBabe
{
    
    
    public enum AllowedSlots
    {
        
        PrimarySlots,
        
        PrimaryAndSecondaryPlainSlots,
        
        PrimaryAndSecondaryVRFSlots,
    }
    
    /// <summary>
    /// >> 134 - Variant[sp_consensus_babe.AllowedSlots]
    /// </summary>
    public sealed class EnumAllowedSlots : BaseEnum<AllowedSlots>
    {
    }
}
